Add database
KlochkovDimka/java-filmorate pull request #8
Opened 2024-03-22 19:22 UTC by KlochkovDimka

Сформирована структура базы данных H2 в файле schema.sql, дополнительные данные в файле data.sql
Созданы Dao классы: FriendshipDbStorageDao.java, GenresFilmsStorageDao.java, LikesFilmsStorageDao.java, MpaStorageDao.java и имплементации их функций: FilmDbStorage.java, FriendshipDbStorageDaoImpl.java, GenresFilmsStorageDaoImpl.java, LikesFilmsStorageDaoImpl.java, MpaStorageDaoImpl.java, UserDbStorage.java
Добавлены контролеры GenreController.java, MpaController.java
Обновлены модели
Добавлены новые исключения NotExistGenreException.java, NotExistMpaBadRequestException.java, NotExistMpaException.java
Добавлены тесты для взаимодействия с базой данных

2024-03-23 19:14 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-03-23 19:14 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@ToString
А зачем разбивать аннотацию `@Data` на три?

2024-03-23 19:14 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +@ToString
Можно использовать аннотацию `@Data`

2024-03-23 19:14 UTC, LexLippi commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS PUBLIC.MPA;
Вот от этого необходимо избавиться, так как ни один пользователь не захочет пользоваться приложением, которое удаляет данные при каждом обновлении

2024-03-23 19:14 UTC, LexLippi commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS PUBLIC.GENRES_FILMS (
Для правильной работы таблиц необходимо, чтобы в них был первичный ключ

2024-03-23 19:14 UTC, LexLippi commented on src/main/resources/schema.sql
> +  STATUS_ID INTEGER,
Могут быть `null`?

2024-03-23 19:14 UTC, LexLippi commented on src/main/resources/data.sql
> +VALUES (2, 'FALSE');
Лучше использовать оператор `merge`

2024-03-23 19:14 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/users/userStorage/UserDbStorage.java
> +        } else {
В `else` нет необходимости, так как мы делаем `return` в основной ветке условного оператора. Эквивалентно будет написать так:

```java
if (userRow.next()) {
            User user = new User(
                    userRow.getInt("id"),
                    userRow.getString("email"),
                    userRow.getString("login"),
                    userRow.getString("name"),
                    userRow.getDate("birthday").toLocalDate());
            user.setId(userRow.getLong("id"));
            return Optional.of(user);
}
throw new NotExistUserException("User not found");
```

2024-03-23 19:14 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/users/userStorage/UserDbStorage.java
> +    private Optional<User> newUser() {
Зачем в таком случае возвращать `Optional`, если он всегда заполнен?

2024-03-23 19:14 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/users/userStorage/UserDbStorage.java
> +        SqlRowSet userRow = jdbcTemplate.queryForRowSet("SELECT * FROM USERS u  ORDER BY u.ID DESC LIMIT 1;");
Зачем `ORDER BY`, если далее делаем `LIMIT 1` это не имеет смысла

2024-03-23 19:14 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/users/userStorage/UserDbStorage.java
> +        } else {
`else` не нужен, аналогично тому, что писал ниже

2024-03-23 19:14 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/users/userStorage/InMemoryUserStorage.java
> +@Qualifier("InMemoryUserStorage")
Можно больше не поддерживать этот компонент

2024-03-23 19:14 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/mpa/impl/MpaStorageDaoImpl.java
> +public class MpaStorageDaoImpl implements MpaStorageDao {
Замечания аналогичные тем, что писал ниже

2024-03-24 19:33 UTC, KlochkovDimka commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/users/userStorage/UserDbStorage.java
> +        SqlRowSet userRow = jdbcTemplate.queryForRowSet("SELECT * FROM USERS u  ORDER BY u.ID DESC LIMIT 1;");
Привет, этот метод возвращал только что сохраненного пользователя в базу данных. Здесь используется ORDER BY DESP с LIMIT 1, чтобы получить последнее добавление в БД

2024-03-25 08:49 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-03-25 20:13 UTC, merged